### ISSUE TITLE
Couple of suggestions 

### ISSUE THREAD

**Issue by omcho420** [Aiuraa/samp-account-lib#1]
As I said in the discord channel I think you should implement this stuff

- Usage of [dakyskye/pawn-env](https://github.com/dakyskye/pawn-env)
I mean that's a suggestion I personally use it, that way your credentials aren't hardcoded + you can change then during runtime etc

- Dialog IDs
Also this won't work as for everyone as a library, I would use y_dialog for this
[Dialogs Enumator](https://github.com/Aiuraa/samp-account-lib/blob/master/test/examples.pwn#L26)
There's like a 99% people already have these dialog id's (0,1,2)

**Comment by Aiuraa** [comment]
Continuing from what i've said in the discord, for now i can't really make any changes to the examples code since it's still for testing until the documentation for this lib is complete.

But i'll keep this in mind, thanks for the suggestions 😄

**Comment by Aiuraa** [comment]
Well, it *might* not using the dakyskye include, but i would try to give the Vince example for making it proper usage.
