### ISSUE TITLE
Database Format Suggestion

### ISSUE THREAD

**Issue by A-ce** [Aiuraa/samp-account-lib#2]
Anyone's free to follow any other format and create the database themselves but it would be great if you could provide people with an example database so they have somewhere to start, rather than to go out of their way to set it up themselves, since a lot of the people using the library will most likely be newbies.

**Comment by Aiuraa** [comment]
Thanks for the suggestions!

> it would be great if you could provide people with an example database so they have somewhere to start, rather than to go out of their way to set it up themselves

This is why I added two methods for the database in `AccLib_Init`, one is manually assigning existing table and the other one is automatically create and assigning the table.

This issue might be related to "Lack of documentation", and I'm planning to add it soon when I'm not busy.
